site_name: DXB110 Notes
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.path
    - toc.integrate   
    - navigation.top
    - search.highlight
    - navigation.tracking
    - navigation.indexes 
    - search.suggest
  plugins:
  - search
markdown_extensions:
  - attr_list