site_name: DXB110 Notes
theme:
  name: material
  icon:
    logo: material/cards-heart
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.path
    - toc.integrate   
    - navigation.top
    - search.highlight
    - navigation.tracking
    - navigation.indexes 
    - search.suggest
  plugins:
    - search
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
